# day3_chunking_research.py

sample_document = """
Retrieval-Augmented Generation (RAG) is a technique that combines information retrieval with text generation.
Instead of relying solely on an LLM's trained parameters, RAG retrieves relevant document chunks from a vector database.

Vector databases like Qdrant store high-dimensional embeddings generated by models like sentence-transformers.
When a user asks a question, the system finds the top-k most similar text chunks and passes them to the LLM.

Chunking is critical because if chunks are too large, the context gets noisy.
If chunks are too small, important surrounding context is lost.
"""

# Strategy 1: Simple Fixed-Size Chunking with Overlap
def fixed_size_chunking(text: str, chunk_size: int = 200, overlap: int = 30) -> list[str]:
    chunks = []
    start = 0
    while start < len(text):
        end = start + chunk_size
        chunk = text[start:end]
        chunks.append(chunk.strip())
        start += chunk_size - overlap
    return chunks

# Strategy 2: Basic Recursive/Semantic Chunking (Splits on double newlines or sentences)
def recursive_semantic_chunking(text: str, max_chunk_size: int = 250) -> list[str]:
    # First split by paragraphs
    paragraphs = [p.strip() for p in text.split("\n\n") if p.strip()]
    chunks = []
    
    for p in paragraphs:
        if len(p) <= max_chunk_size:
            chunks.append(p)
        else:
            # If paragraph is too long, split by sentences
            sentences = p.split(". ")
            current_chunk = ""
            for sentence in sentences:
                if len(current_chunk) + len(sentence) <= max_chunk_size:
                    current_chunk += sentence + ". "
                else:
                    chunks.append(current_chunk.strip())
                    current_chunk = sentence + ". "
            if current_chunk:
                chunks.append(current_chunk.strip())
                
    return chunks

if __name__ == "__main__":
    print("=== Strategy 1: Fixed-Size Chunks ===")
    fixed_chunks = fixed_size_chunking(sample_document, chunk_size=200, overlap=30)
    for i, c in enumerate(fixed_chunks, 1):
        print(f"Chunk {i} ({len(c)} chars):\n'{c}'\n")

    print("\n=== Strategy 2: Recursive / Semantic Chunks ===")
    semantic_chunks = recursive_semantic_chunking(sample_document, max_chunk_size=250)
    for i, c in enumerate(semantic_chunks, 1):
        print(f"Chunk {i} ({len(c)} chars):\n'{c}'\n")