"""
General file-system helper functions.

These are small, single-purpose functions used by the upload and
parsing services. Keeping them here (instead of copy-pasting the same
logic in multiple services) is what "reusable" means in practice.
"""

import json
import re
import uuid
from pathlib import Path

from app.core.config import settings
from app.core.exceptions import FileTooLargeError, InvalidFileIdError, InvalidFileTypeError
from app.core.logger import logger

# file_id is always generated by generate_file_id() below, which produces
# a 32-character lowercase hex string (uuid4().hex). Any file_id that does
# not match this pattern did not come from our own /upload endpoint and
# must be rejected before it is used to build a filesystem path - this is
# what prevents path traversal via a crafted file_id like "../../etc/passwd".
_FILE_ID_PATTERN = re.compile(r"^[a-f0-9]{32}$")

# The first bytes of every valid PDF file start with this signature,
# regardless of what extension the file was given. Checking this catches
# a non-PDF file that was simply renamed to end in ".pdf".
_PDF_MAGIC_BYTES = b"%PDF-"


def generate_file_id() -> str:
    """
    Create a short unique identifier for an uploaded file.

    We use uuid4 (randomly generated UUID) so that two files uploaded
    at the same moment never collide, even under concurrent requests.
    """
    return uuid.uuid4().hex


def validate_file_id(file_id: str) -> None:
    """
    Confirm a file_id path parameter has the exact shape our own
    generate_file_id() produces.

    Raises:
        InvalidFileIdError: if the value does not match a 32-character
        hex string. This must be called before file_id is ever used
        to build a Path, to prevent path traversal.
    """
    if not _FILE_ID_PATTERN.match(file_id):
        logger.warning(f"Rejected malformed or unsafe file_id: {file_id!r}")
        raise InvalidFileIdError("file_id is not valid.")


def validate_pdf_extension(filename: str) -> None:
    """
    Confirm the uploaded file has a .pdf extension.

    Raises:
        InvalidFileTypeError: if the extension is not in the allowed set.
    """
    extension = Path(filename).suffix.lower()
    if extension not in settings.ALLOWED_EXTENSIONS:
        logger.warning(f"Rejected upload with invalid extension: {filename}")
        raise InvalidFileTypeError(
            f"Unsupported file type '{extension}'. Only PDF files are accepted."
        )


def validate_pdf_content(content: bytes) -> None:
    """
    Confirm the uploaded bytes actually look like a PDF, regardless of
    what extension the file was given.

    A correct extension is not proof of correct content - someone can
    rename any file to end in ".pdf". This checks the real file
    signature instead of trusting the filename alone.

    Raises:
        InvalidFileTypeError: if the content does not start with the
        standard PDF file signature.
    """
    if not content.startswith(_PDF_MAGIC_BYTES):
        logger.warning("Rejected upload whose content is not a valid PDF")
        raise InvalidFileTypeError(
            "File content does not match a valid PDF file."
        )


def validate_file_size(size_bytes: int) -> None:
    """
    Confirm the uploaded file does not exceed the configured size limit.

    Raises:
        FileTooLargeError: if the file is larger than settings.MAX_FILE_SIZE_BYTES.
    """
    if size_bytes > settings.MAX_FILE_SIZE_BYTES:
        logger.warning(f"Rejected upload of {size_bytes} bytes, exceeds limit")
        raise FileTooLargeError(
            f"File exceeds the maximum allowed size of {settings.MAX_FILE_SIZE_MB} MB."
        )


def build_upload_path(file_id: str) -> Path:
    """
    Build the on-disk path where an uploaded PDF with the given ID
    should be stored. Every uploaded file is renamed to <file_id>.pdf
    so that the original filename (which may contain spaces, unicode
    characters, or path-unsafe characters) never touches the filesystem.
    """
    return settings.UPLOAD_DIR / f"{file_id}.pdf"


def save_uploaded_file(file_id: str, content: bytes) -> Path:
    """
    Write uploaded file bytes to disk under the uploads/ directory.

    Args:
        file_id: unique identifier generated for this upload.
        content: raw bytes of the uploaded file.

    Returns:
        The path the file was saved to.
    """
    destination = build_upload_path(file_id)
    destination.write_bytes(content)
    logger.info(f"Saved uploaded file to {destination}")
    return destination


# Read uploads in fixed-size chunks rather than loading the whole file
# into memory at once. 1 MB is small enough to keep memory usage low
# even for a very large upload, and large enough that we are not
# making an excessive number of read calls for a normal-sized PDF.
_UPLOAD_CHUNK_SIZE = 1024 * 1024


async def save_uploaded_file_streamed(file_id: str, upload_file) -> int:
    """
    Write an uploaded file to disk in chunks instead of buffering the
    entire upload in memory before validating it.

    As each chunk arrives we check the running total against the
    configured size limit, and check the very first chunk against the
    PDF file signature. Either failure aborts immediately, deletes the
    partial file, and raises - so an oversized or invalid upload never
    ends up fully sitting in RAM or occupying disk space.

    Args:
        file_id: unique identifier generated for this upload.
        upload_file: a FastAPI/Starlette UploadFile, or anything with
            an async .read(size) method.

    Returns:
        Total number of bytes written.

    Raises:
        FileTooLargeError: if the upload exceeds settings.MAX_FILE_SIZE_BYTES.
        InvalidFileTypeError: if the content does not start with the PDF signature.
    """
    destination = build_upload_path(file_id)
    total_bytes = 0
    is_first_chunk = True

    try:
        with open(destination, "wb") as output_file:
            while True:
                chunk = await upload_file.read(_UPLOAD_CHUNK_SIZE)
                if not chunk:
                    break

                if is_first_chunk:
                    validate_pdf_content(chunk)
                    is_first_chunk = False

                total_bytes += len(chunk)
                validate_file_size(total_bytes)

                output_file.write(chunk)

    except (FileTooLargeError, InvalidFileTypeError):
        # Do not leave a partial/invalid file behind on disk.
        destination.unlink(missing_ok=True)
        raise

    logger.info(f"Saved uploaded file to {destination} ({total_bytes} bytes)")
    return total_bytes


def get_uploaded_file_path(file_id: str) -> Path:
    """
    Resolve the path of a previously uploaded file from its ID.

    Raises:
        FileNotFoundError: if no file with this ID exists on disk.
    """
    path = build_upload_path(file_id)
    if not path.exists():
        raise FileNotFoundError(f"No uploaded file found for id '{file_id}'")
    return path


def ensure_output_subfolder(base_dir: Path, file_id: str) -> Path:
    """
    Create (if needed) and return a per-file subfolder inside a given
    output directory, e.g. output/images/<file_id>/. This keeps output
    from different PDFs from mixing together in the same folder.
    """
    subfolder = base_dir / file_id
    subfolder.mkdir(parents=True, exist_ok=True)
    return subfolder


def _build_registry_path(file_id: str) -> Path:
    """Path to the small sidecar JSON file that remembers upload details."""
    return settings.UPLOAD_DIR / f"{file_id}.meta.json"


def save_original_filename(file_id: str, original_filename: str) -> None:
    """
    Remember the filename a file was originally uploaded as.

    We rename every upload to <file_id>.pdf on disk, so without this
    the original name would be lost, and /parse/{file_id} would have
    no way to know it and would have to blindly trust whatever
    filename the caller of /parse claims - which may not be the file
    that was actually uploaded.
    """
    registry_path = _build_registry_path(file_id)
    registry_path.write_text(
        json.dumps({"original_filename": original_filename}),
        encoding="utf-8",
    )


def get_original_filename(file_id: str, default: str = "document.pdf") -> str:
    """
    Look up the filename a file was originally uploaded as.

    Returns the default if no registry entry exists, for example if
    the upload happened before this feature existed.
    """
    registry_path = _build_registry_path(file_id)
    if not registry_path.exists():
        return default

    try:
        data = json.loads(registry_path.read_text(encoding="utf-8"))
        return data.get("original_filename", default)
    except (json.JSONDecodeError, OSError):
        logger.warning(f"Could not read filename registry for {file_id}")
        return default
